package com.ljt.dao;

import com.ljt.bean.Selectedcourse;
import com.ljt.bean.SelectedcourseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SelectedcourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbg.generated Tue Sep 17 22:29:08 CST 2019
     */
    long countByExample(SelectedcourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbg.generated Tue Sep 17 22:29:08 CST 2019
     */
    int deleteByExample(SelectedcourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbg.generated Tue Sep 17 22:29:08 CST 2019
     */
    int insert(Selectedcourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbg.generated Tue Sep 17 22:29:08 CST 2019
     */
    int insertSelective(Selectedcourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbg.generated Tue Sep 17 22:29:08 CST 2019
     */
    List<Selectedcourse> selectByExample(SelectedcourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbg.generated Tue Sep 17 22:29:08 CST 2019
     */
    int updateByExampleSelective(@Param("record") Selectedcourse record, @Param("example") SelectedcourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbg.generated Tue Sep 17 22:29:08 CST 2019
     */
    int updateByExample(@Param("record") Selectedcourse record, @Param("example") SelectedcourseExample example);
}