package com.ljt.dao;

import com.ljt.bean.Userlogin;
import com.ljt.bean.UserloginExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserloginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbg.generated Tue Sep 17 22:29:08 CST 2019
     */
    long countByExample(UserloginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbg.generated Tue Sep 17 22:29:08 CST 2019
     */
    int deleteByExample(UserloginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbg.generated Tue Sep 17 22:29:08 CST 2019
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbg.generated Tue Sep 17 22:29:08 CST 2019
     */
    int insert(Userlogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbg.generated Tue Sep 17 22:29:08 CST 2019
     */
    int insertSelective(Userlogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbg.generated Tue Sep 17 22:29:08 CST 2019
     */
    List<Userlogin> selectByExample(UserloginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbg.generated Tue Sep 17 22:29:08 CST 2019
     */
    Userlogin selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbg.generated Tue Sep 17 22:29:08 CST 2019
     */
    int updateByExampleSelective(@Param("record") Userlogin record, @Param("example") UserloginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbg.generated Tue Sep 17 22:29:08 CST 2019
     */
    int updateByExample(@Param("record") Userlogin record, @Param("example") UserloginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbg.generated Tue Sep 17 22:29:08 CST 2019
     */
    int updateByPrimaryKeySelective(Userlogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlogin
     *
     * @mbg.generated Tue Sep 17 22:29:08 CST 2019
     */
    int updateByPrimaryKey(Userlogin record);
}