package com.ljt.bean;

public class College {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college.collegeID
     *
     * @mbg.generated Tue Sep 17 22:29:08 CST 2019
     */
    private Integer collegeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college.collegeName
     *
     * @mbg.generated Tue Sep 17 22:29:08 CST 2019
     */
    private String collegename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.collegeID
     *
     * @return the value of college.collegeID
     *
     * @mbg.generated Tue Sep 17 22:29:08 CST 2019
     */
    public Integer getCollegeid() {
        return collegeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.collegeID
     *
     * @param collegeid the value for college.collegeID
     *
     * @mbg.generated Tue Sep 17 22:29:08 CST 2019
     */
    public void setCollegeid(Integer collegeid) {
        this.collegeid = collegeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.collegeName
     *
     * @return the value of college.collegeName
     *
     * @mbg.generated Tue Sep 17 22:29:08 CST 2019
     */
    public String getCollegename() {
        return collegename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.collegeName
     *
     * @param collegename the value for college.collegeName
     *
     * @mbg.generated Tue Sep 17 22:29:08 CST 2019
     */
    public void setCollegename(String collegename) {
        this.collegename = collegename == null ? null : collegename.trim();
    }

	@Override
	public String toString() {
		return "College [collegeid=" + collegeid + ", collegename=" + collegename + "]";
	}
}