package com.ljt.bean;

public class Selectedcourse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column selectedcourse.courseID
     *
     * @mbg.generated Tue Sep 17 22:29:08 CST 2019
     */
    private Integer courseid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column selectedcourse.studentID
     *
     * @mbg.generated Tue Sep 17 22:29:08 CST 2019
     */
    private Integer studentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column selectedcourse.mark
     *
     * @mbg.generated Tue Sep 17 22:29:08 CST 2019
     */
    private Integer mark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column selectedcourse.courseID
     *
     * @return the value of selectedcourse.courseID
     *
     * @mbg.generated Tue Sep 17 22:29:08 CST 2019
     */
    public Integer getCourseid() {
        return courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column selectedcourse.courseID
     *
     * @param courseid the value for selectedcourse.courseID
     *
     * @mbg.generated Tue Sep 17 22:29:08 CST 2019
     */
    public void setCourseid(Integer courseid) {
        this.courseid = courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column selectedcourse.studentID
     *
     * @return the value of selectedcourse.studentID
     *
     * @mbg.generated Tue Sep 17 22:29:08 CST 2019
     */
    public Integer getStudentid() {
        return studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column selectedcourse.studentID
     *
     * @param studentid the value for selectedcourse.studentID
     *
     * @mbg.generated Tue Sep 17 22:29:08 CST 2019
     */
    public void setStudentid(Integer studentid) {
        this.studentid = studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column selectedcourse.mark
     *
     * @return the value of selectedcourse.mark
     *
     * @mbg.generated Tue Sep 17 22:29:08 CST 2019
     */
    public Integer getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column selectedcourse.mark
     *
     * @param mark the value for selectedcourse.mark
     *
     * @mbg.generated Tue Sep 17 22:29:08 CST 2019
     */
    public void setMark(Integer mark) {
        this.mark = mark;
    }

	@Override
	public String toString() {
		return "Selectedcourse [courseid=" + courseid + ", studentid=" + studentid + ", mark=" + mark + "]";
	}
}